name: Upload all velog posts by series

on:
  workflow_dispatch:

jobs:
  upload_all_velog_posts_by_series:
    runs-on: ubuntu-latest

    steps:
      # 리포지토리 체크아웃 (버전 업데이트 v2 -> v4)
      - name: Checkout
        uses: actions/checkout@v4

      # Git Config 설정
      - name: Set up Git
        run: |
          git config --global user.name 'Molly-Dooker'
          git config --global user.email 'room0729@gmail.com'
          git remote set-url origin https://Molly-Dooker:${{ secrets.GH_PAT }}@github.com/Molly-Dooker/velog.git

      # 원격 변경 사항을 로컬에 적용
      - name: Pull changes from remote
        run: |
          git pull --rebase origin main

      # Python 3.9 설정 (버전 업데이트 v2 -> v5)
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # 필요한 Python 의존성 설치
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser gitpython requests

      # Python 스크립트 실행
      - name: Run script
        env:
          VELOG_ID: "notepad"
        run: |
          python ./scripts/batch_velog_posts_by_series/main.py
